paths:
  uploads: public/images/portfolio
  static: public
collections_config:
  productos:
    path: public/productos
    output: false
    icon: shopping_cart
    allow_create: true
    # AQU√ç CONFIGURAMOS EL SELECTOR
    fields:
      category:
        type: select
        options:
          values:
            - Camisas
            - Tazas
            - Sublimados
            - Otros
      image:
        type: image
      price:
        type: number
      description:
        type: textarea
